version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            chmod +x miniconda.sh && ./miniconda.sh -b -p ~/miniconda
            export PATH="~/miniconda/bin:$PATH"
            conda update --yes --quiet conda
            conda create -n testenv --yes --quiet python=3.10
            source activate testenv
            pip install catboost==1.1.1 hyperopt==0.2.7 lightgbm==3.3.5 numpy==1.23.3 numpydoc pandas==1.5.0 scikit-learn==1.1.2 sphinx sphinx-gallery sphinx_rtd_theme pillow pytest pytest-cov xgboost==1.6.2 
            pip install .
            cd doc
            make html
      - store_artifacts:
          path: doc/_build/html/
          destination: doc
      - store_artifacts:
          path: ~/log.txt
      - run: ls -ltrh doc/_build/html
    filters:
      branches:
        ignore: gh-pages
        
  
workflows:
  version: 2
  workflow:
    jobs:
      - build
